### PR TITLE
Recover 24 words support

### PR DESCRIPTION
**Pull request by yshwanth**
Updated the code for 24 import seed words

### CODE REVIEW

**Comment by i5hi** [comment]
Thanks for the PR @yshwanth 

Few checkpoints:

- [ ] Test Importing both valid/invalid 24 word mnemonic
- [ ] Show appropriate error if all 24 words are not filled
- [ ] Import Wallets do not need to Backup but they can Test Backup - in Test Backup Update UI to say 12/24 words and ensure that a 24 word mnemonic is displayed correctly.

**Comment by yshwanth** [comment]
Yes, I need to test and update various error cases and also few changes to code for smooth and clean UX

**Comment by yshwanth** [comment]
Choose/ select option radio button page
12 words 
24 words

If a user enters 12 words then after clicking on 24 words ,user has to type it once again, which is bad UX.

**Comment by yshwanth** [comment]
checkpoints done:

    [x]  Test Importing both valid/invalid 24 word mnemonic
    [x]  Show appropriate error if all 24 words are not filled
    [x]  Import Wallets do not need to Backup but they can Test Backup - in Test Backup Update UI to say 12/24 words and  ensure that a 24 word mnemonic is displayed correctly.

**Comment by i5hi** [comment]
Thanks Yashwanth! Checking out your PR now.

**Comment by i5hi** [comment]
Everything is working as expected. 

Congratulations and thanks for your first PR!

**Pull request merged**
