### PR TITLE
refactor: Untrack generated files

### PR DESCRIPTION
**Pull request by ethicnology**
This pull request remove all `freezed.dart` and `g.dart` files from version control.
These files are unnecessary tracked, they can be regenerated by the following commands:

- `flutter pub run build_runner build --delete-conflicting-outputs` (deprecated)
- `dart run build_runner build --delete-conflicting-outputs` (preferred)

This changes may break the current continuous integrations. I can't see/trigger the actions in this repo but we will probably need to update them with an extra step:
`run: dart run build_runner build --delete-conflicting-outputs`

### CODE REVIEW

**Comment by mocodesmo** [comment]
@ethicnology  what are the benefits of doing this ? is a quality of life improvement ? 

personally i prefer the generated files commit being in git because i don't need to keep the build_runner on while pulling.
this forces developers to keep build_runner on while using git 

but i'm open to it if there is good reasoning

**Comment by ethicnology** [comment]
@mocodesmo 

> what are the benefits of doing this ? is a quality of life improvement ?

Generally, you should gitignore all files that can be generated in a deterministic way. Generated files can bloat the repository size over time, especially for projects with frequent updates to these files. In this case, we have 20k unnecessary lines tracked. 

On my personal experience, I find it really annoying when it comes to commit to have unnecessary files appearing in my changes while I want to focus on the files that really matters.

> personally i prefer the generated files commit being in git because i don't need to keep the build_runner on while pulling. this forces developers to keep build_runner on while using git

I get it, but if the developer has to create/modify a freezed class, he will have to execute the command anyway

> Also every commit will always have compiler errors

Until you execute the command, it's a like a getting the dependencies, when you clone a flutter repository you have compilator errors until you execute `flutter pub get`. Same if you `checkout/pull` a branch with a dependencies changes.

> Is it given in the freezed docs or flutter docs that generated files shouldn't be commited ?

Maintainer: ["That's up to you. There's no official answer"](https://github.com/rrousselGit/freezed/discussions/943#discussioncomment-6332685)

But, the [example repository](https://github.com/rrousselGit/freezed/tree/744ac93f97ff2370de00e1d16fe30658aa6345ba/packages/freezed/example) showcased excludes generated files from in the [.gitignore](https://github.com/rrousselGit/freezed/blob/744ac93f97ff2370de00e1d16fe30658aa6345ba/packages/freezed/example/.gitignore#L1)

**Comment by i5hi** [comment]
I'm open to removing them. Lets try it out and see if it makes things easier.

**Comment by ethicnology** [comment]
rebased on main

**Comment by DanGould** [comment]
Are you able to run this commit in simulator? I'm getting an error even after running `dart run build_runner build --delete-conflicting-outputs` on 0acf3e4669ce8a11b6d5a712c397a7bd611951d5


```
Running Gradle task 'assembleDebug'...                          
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

lib/_pkg/wallet/lwk/sync.dart:12:51: Error: No named parameter with the name 'validateDomain'.
    await lwkWallet.sync(electrumUrl: blockChain, validateDomain: true);
                                                  ^^^^^^^^^^^^^^
lib/_pkg/wallet/lwk/sync.dart:67:53: Error: No named parameter with the name 'validateDomain'.
      await lwkWallet.sync(electrumUrl: blockChain, validateDomain: true);
                                                    ^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.
```

**Comment by ethicnology** [comment]
@DanGould I had the same problem, it's related to https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/347

**Pull request merged**
